AllCops:
  Exclude:
    - "bin/**/*"
    - "vendor/**/*"
    - "node_modules/**/*"
    - "test/scratch/**/*"
  TargetRubyVersion: 2.7

require:
  - rubocop-performance
  - rubocop-rails

Rails:
  Enabled: true

Security:
  Enabled: true

Performance:
  Enabled: true

Layout:
  Enabled: false

Metrics:
  Enabled: false

Naming/MemoizedInstanceVariableName:
  Enabled: false

Lint/AmbiguousBlockAssociation:
  Enabled: false

Rails/UnknownEnv:
  Environments:
    - production
    - development
    - test
    - integration_test

Bundler/OrderedGems:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: true
  EnforcedStyle: always

Style/StringLiterals:
  Enabled: false

Style/TrailingCommaInHashLiteral:
  Enabled: false

Style/TrailingCommaInArguments:
  Enabled: false

Style/HashSyntax:
  Enabled: false

Style/HashEachMethods:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true

Style/NumericLiterals:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Style/RedundantParentheses:
  Enabled: false

Style/GuardClause:
  Enabled: false

Style/Documentation:
  Enabled: true
  Severity: warning
  Exclude:
    - spec/**/*
    - test/**/*
    - db/**/*
    - app/graphql/**/*
    - app/helpers/**/*
    - app/jobs/**/*

Style/RedundantSelf:
  Enabled: false

Style/DoubleNegation:
  Enabled: false

Style/NegatedIf:
  Enabled: false

Style/Next:
  Enabled: false

Style/TrailingUnderscoreVariable:
  Enabled: false

Style/EmptyMethod:
  Enabled: false

Style/StringLiteralsInInterpolation:
  Enabled: false

Style/TrailingCommaInArrayLiteral:
  Enabled: false

Style/NumericPredicate:
  Enabled: false

Rails/FilePath:
  Enabled: false

# For Rails' autoloading, the nested module::class style triggers autoloading of the module, which is necessary in some instances.
Style/ClassAndModuleChildren:
  Enabled: true
  Include:
    - test/**/*
  EnforcedStyle: compact